### PR TITLE
http,mixins: Add formatted HTTP string

### PR DESCRIPTION
**Pull request by netanelc305**
## Added Features
Added prettier http message format. 

I think it should replace the `__str__` but i didn't want to override it.

### CODE REVIEW

**Comment by Cyb3r-Jak3** [comment]
Hi @netanelc305
Thanks for the second PR. Can you fix the lint issues and add new unit test to cover your additions.?

**Review by Cyb3r-Jak3 — CHANGES_REQUESTED** [review]
See comment for fixing

**Comment by netanelc305** [comment]
@Cyb3r-Jak3  Done

**Review by Cyb3r-Jak3 — APPROVED** [review]

**Comment by netanelc305** [comment]
Hi , are you planing to release a new version anytime soon?
i have another project depend on this PR.

**Comment by Cyb3r-Jak3** [comment]
I've just released v2.3.0 which includes this PR

**Pull request merged**
