### PR TITLE
allow 'pages' property is missing in log object

### PR DESCRIPTION
**Pull request by yysushi**
## Bug Fixes

according to har 1.2 spec, 'pages' property in log object is optional.
however this library assumes the existence. this PR let it collect all entries in unknown page in such case

### CODE REVIEW

**Comment by yysushi** [comment]
https://github.com/haralyzer/haralyzer/issues/50

**Comment by Cyb3r-Jak3** [comment]
@yysushi Thanks for the PR. Can you please merge the latest master into your branch to update the version that is being tested on?

**Comment by yysushi** [comment]
Hi @Cyb3r-Jak3 thanks for the quick confirmation.
I rebased and pushed my code.
looks like lint and test passed as far as I executed in my laptop.

<details>
<summary> logs </summary>

- make lint
```bash
yysushi: ~/g/g/y/haralyzer (missing_page)$ git log -1 --oneline
8f44f5f (HEAD -> missing_page, origin/missing_page) fix the exception issue, where 'pages' property is missing in log object
yysushi: ~/g/g/y/haralyzer (missing_page)$ make lint
black --check haralyzer
All done! ✨ 🍰 ✨
6 files would be left unchanged.
pylint --disable=E1101,C0103,W0511,R0901 haralyzer

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

flake8 --max-line-length 89 --statistics --show-source --count haralyzer
0
bandit -r haralyzer
[main]  INFO    profile include tests: None
[main]  INFO    profile exclude tests: None
[main]  INFO    cli include tests: None
[main]  INFO    cli exclude tests: None
[main]  INFO    running on Python 3.9.9
Run started:2022-12-04 01:21:13.053049

Test results:
        No issues identified.

Code scanned:
        Total lines of code: 1380
        Total lines skipped (#nosec): 0

Run metrics:
        Total issues (by severity):
                Undefined: 0.0
                Low: 0.0
                Medium: 0.0
                High: 0.0
        Total issues (by confidence):
                Undefined: 0.0
                Low: 0.0
                Medium: 0.0
                High: 0.0
Files skipped (0):
ysushi: ~/g/g/y/haralyzer (missing_page)$ echo $?
0
```

- make test
```bash
yysushi: ~/g/g/y/haralyzer (missing_page)$ make test
py.test --cov haralyzer tests/ -vv
============================================================================================================ test session starts =============================================================================================================
platform darwin -- Python 3.9.9, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /nix/store/crajbxw47xx02nyqws6k2w2fxhfk449w-python3-3.9.9-env/bin/python3.9
cachedir: .pytest_cache
rootdir: /Users/y-tsuji/git/github.com/yysushi/haralyzer
plugins: cov-3.0.0
collected 60 items

tests/test_entry.py::test_entry PASSED                                                                                                                                                                                                 [  1%]
tests/test_entry.py::test_request PASSED                                                                                                                                                                                               [  3%]
tests/test_entry.py::test_response PASSED                                                                                                                                                                                              [  5%]
tests/test_entry.py::test_backwards PASSED                                                                                                                                                                                             [  6%]
tests/test_multi_parser.py::test_init PASSED                                                                                                                                                                                           [  8%]
tests/test_multi_parser.py::test_load_times PASSED                                                                                                                                                                                     [ 10%]
tests/test_multi_parser.py::test_stdev PASSED                                                                                                                                                                                          [ 11%]
tests/test_page.py::test_init PASSED                                                                                                                                                                                                   [ 13%]
tests/test_page.py::test_no_title PASSED                                                                                                                                                                                               [ 15%]
tests/test_page.py::test_filter_entries PASSED                                                                                                                                                                                         [ 16%]
tests/test_page.py::test_filter_entries_load_time PASSED                                                                                                                                                                               [ 18%]
tests/test_page.py::test_get_load_time PASSED                                                                                                                                                                                          [ 20%]
tests/test_page.py::test_entries PASSED                                                                                                                                                                                                [ 21%]
tests/test_page.py::test_iteration PASSED                                                                                                                                                                                              [ 23%]
tests/test_page.py::test_file_types PASSED                                                                                                                                                                                             [ 25%]
tests/test_page.py::test_request_types PASSED                                                                                                                                                                                          [ 26%]
tests/test_page.py::test_sizes_trans PASSED                                                                                                                                                                                            [ 28%]
tests/test_page.py::test_sizes PASSED                                                                                                                                                                                                  [ 30%]
tests/test_page.py::test_load_times PASSED                                                                                                                                                                                             [ 31%]
tests/test_page.py::test_time_to_first_byte PASSED                                                                                                                                                                                     [ 33%]
tests/test_page.py::test_hostname PASSED                                                                                                                                                                                               [ 35%]
tests/test_page.py::test_url PASSED                                                                                                                                                                                                    [ 36%]
tests/test_page.py::test_duplicate_urls_count PASSED                                                                                                                                                                                   [ 38%]
tests/test_parser.py::test_init PASSED                                                                                                                                                                                                 [ 40%]
tests/test_parser.py::test_from_file PASSED                                                                                                                                                                                            [ 41%]
tests/test_parser.py::test_from_string PASSED                                                                                                                                                                                          [ 43%]
tests/test_parser.py::test_init_entry_with_no_pageref PASSED                                                                                                                                                                           [ 45%]
tests/test_parser.py::test_init_entry_with_no_page PASSED                                                                                                                                                                              [ 46%]
tests/test_parser.py::test_match_headers PASSED                                                                                                                                                                                        [ 48%]
tests/test_parser.py::test_match_request_type PASSED                                                                                                                                                                                   [ 50%]
tests/test_parser.py::test_match_status_code PASSED                                                                                                                                                                                    [ 51%]
tests/test_parser.py::test_http_version PASSED                                                                                                                                                                                         [ 53%]
tests/test_parser.py::test_match_content_type PASSED                                                                                                                                                                                   [ 55%]
tests/test_parser.py::test_create_asset_timeline PASSED                                                                                                                                                                                [ 56%]
tests/chrome/test_chrome_entry.py::test_entry PASSED                                                                                                                                                                                   [ 58%]
tests/chrome/test_chrome_entry.py::test_request PASSED                                                                                                                                                                                 [ 60%]
tests/chrome/test_chrome_entry.py::test_response PASSED                                                                                                                                                                                [ 61%]
tests/chrome/test_chrome_entry.py::test_backwards PASSED                                                                                                                                                                               [ 63%]
tests/chrome/test_chrome_page.py::test_init PASSED                                                                                                                                                                                     [ 65%]
tests/chrome/test_chrome_page.py::test_filter_entries PASSED                                                                                                                                                                           [ 66%]
tests/chrome/test_chrome_page.py::test_entries PASSED                                                                                                                                                                                  [ 68%]
tests/chrome/test_chrome_page.py::test_request_types PASSED                                                                                                                                                                            [ 70%]
tests/chrome/test_chrome_page.py::test_load_times PASSED                                                                                                                                                                               [ 71%]
tests/chrome/test_chrome_page.py::test_time_to_first_byte PASSED                                                                                                                                                                       [ 73%]
tests/chrome/test_chrome_page.py::test_hostname PASSED                                                                                                                                                                                 [ 75%]
tests/chrome/test_chrome_page.py::test_url PASSED                                                                                                                                                                                      [ 76%]
tests/chrome/test_chrome_page.py::test_redirect PASSED                                                                                                                                                                                 [ 78%]
tests/firefox/test_firefox_entry.py::test_entry PASSED                                                                                                                                                                                 [ 80%]
tests/firefox/test_firefox_entry.py::test_request PASSED                                                                                                                                                                               [ 81%]
tests/firefox/test_firefox_entry.py::test_response PASSED                                                                                                                                                                              [ 83%]
tests/firefox/test_firefox_entry.py::test_backwards PASSED                                                                                                                                                                             [ 85%]
tests/firefox/test_firefox_page.py::test_init PASSED                                                                                                                                                                                   [ 86%]
tests/firefox/test_firefox_page.py::test_filter_entries PASSED                                                                                                                                                                         [ 88%]
tests/firefox/test_firefox_page.py::test_get_load_time PASSED                                                                                                                                                                          [ 90%]
tests/firefox/test_firefox_page.py::test_entries PASSED                                                                                                                                                                                [ 91%]
tests/firefox/test_firefox_page.py::test_request_types PASSED                                                                                                                                                                          [ 93%]
tests/firefox/test_firefox_page.py::test_load_times PASSED                                                                                                                                                                             [ 95%]
tests/firefox/test_firefox_page.py::test_time_to_first_byte PASSED                                                                                                                                                                     [ 96%]
tests/firefox/test_firefox_page.py::test_hostname PASSED                                                                                                                                                                               [ 98%]
tests/firefox/test_firefox_page.py::test_url PASSED                                                                                                                                                                                    [100%]

---------- coverage: platform darwin, python 3.9.9-final-0 -----------
Name                    Stmts   Miss  Cover
-------------------------------------------
haralyzer/__init__.py       3      0   100%
haralyzer/assets.py       399      4    99%
haralyzer/errors.py         1      0   100%
haralyzer/http.py          97      0   100%
haralyzer/mixins.py        27      0   100%
haralyzer/multihar.py      80      0   100%
-------------------------------------------
TOTAL                     607      4    99%


============================================================================================================= 60 passed in 8.57s =============================================================================================================
```
</details>

could you trigger tests by github action in your side? (I have no permission on that)

**Comment by Cyb3r-Jak3** [comment]
Looks like there is a bug with the action where it fails to report code coverage. All the linting and tests pass, though, so I'll patch it later. 

Thanks again for the PR!

**Review by Cyb3r-Jak3 — APPROVED** [review]

**Pull request merged**
